apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: prometheus-community
  pass_credentials_all: false
  password: ""
  url: https://prometheus-community.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: homarr-labs
  pass_credentials_all: false
  password: ""
  url: https://homarr-labs.github.io/charts/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: selfhosted-helmcharts
  pass_credentials_all: false
  password: ""
  url: https://vyrtualsynthese.github.io/selfhosted-helmcharts/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: oben01
  pass_credentials_all: false
  password: ""
  url: https://oben01.github.io/charts/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: longhorn
  pass_credentials_all: false
  password: ""
  url: https://charts.longhorn.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: homarr
  pass_credentials_all: false
  password: ""
  url: https://homarr-labs.github.io/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: nextcloud
  pass_credentials_all: false
  password: ""
  url: https://nextcloud.github.io/helm/
  username: ""
